#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/godot_project/scripts/GeneratedSecrets.gd"

load_env_file() {
  local env_path="$1"
  [[ -f "$env_path" ]] || return 0

  while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
    local line="${raw_line#"${raw_line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" || "${line:0:1}" == "#" ]] && continue
    [[ "$line" == *=* ]] || continue

    local key="${line%%=*}"
    local value="${line#*=}"
    key="${key%"${key##*[![:space:]]}"}"
    key="${key#"${key%%[![:space:]]*}"}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"

    if [[ -n "$value" && "${value:0:1}" == "'" && "${value: -1}" == "'" ]]; then
      value="${value:1:${#value}-2}"
    elif [[ -n "$value" && "${value:0:1}" == '"' && "${value: -1}" == '"' ]]; then
      value="${value:1:${#value}-2}"
    fi

    if [[ -z "${!key:-}" ]]; then
      export "$key=$value"
    fi
  done < "$env_path"
}

resolve_public_base_url() {
  if [[ -n "${PUBLIC_BASE_URL:-}" ]]; then
    printf '%s' "${PUBLIC_BASE_URL%/}"
    return 0
  fi

  local candidates=(
    "/etc/secrets/.env"
    "/etc/secrets/.env.secret"
    "/etc/secrets/.env.public"
    "$ROOT_DIR/.env.public"
    "$ROOT_DIR/.env"
    "$ROOT_DIR/.env.secret"
  )

  local candidate=""
  for candidate in "${candidates[@]}"; do
    load_env_file "$candidate"
    if [[ -n "${PUBLIC_BASE_URL:-}" ]]; then
      printf '%s' "${PUBLIC_BASE_URL%/}"
      return 0
    fi
  done

  return 1
}

if ! resolved_public_base_url="$(resolve_public_base_url)"; then
  echo "[error] PUBLIC_BASE_URL is not set in the shell or any supported env file." >&2
  exit 1
fi

if [[ "$resolved_public_base_url" != http://* && "$resolved_public_base_url" != https://* ]]; then
  echo "[error] PUBLIC_BASE_URL must start with http:// or https:// (got '$resolved_public_base_url')." >&2
  exit 1
fi

cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by scripts/generate_godot_runtime_config.sh
# Do not edit manually.

const PROD_URL = "$resolved_public_base_url"
EOF

echo "[done] Generated $OUTPUT_FILE from PUBLIC_BASE_URL=$resolved_public_base_url"
